services:
  octoprint1:
    image: octoprint/octoprint:latest
    container_name: octoprint1
    ports:
      - "5001:80"
    volumes:
      - octo1_data:/octoprint
    networks: [stack]
    restart: unless-stopped

  octoprint2:
    image: octoprint/octoprint:latest
    container_name: octoprint2
    ports:
      - "5002:80"
    volumes:
      - octo2_data:/octoprint
    networks: [stack]
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fdmmroot
      - MONGO_INITDB_ROOT_PASSWORD=fdmmsecret
    volumes:
      - ./mongodb-data:/data/db
      - ./mongoconfig:/data/configdb
    networks: [stack]

  fdm-monster:
    build: .
    container_name: fdm-monster
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    environment:
      - MONGO=mongodb://fdmmroot:fdmmsecret@mongodb:27017/fdm-monster?authSource=admin
    volumes:
      - ./fdm-monster/media:/app/media
    networks: [stack]

volumes:
  octo1_data:
  octo2_data:

networks:
  stack:
